### ISSUE TITLE
Peerdependecy automatic installation

### ISSUE THREAD

**Issue by LeonNimoy** [senecajs/seneca-refer#4]
Hey, @rjrodger!

I'm having a little issue between Node.js/NPM and peerDependencies.  
Currently, the package.json relies on the npm7+ feature which installs all listed peerDependencies. The peerDependencies aren't declared in the devDependencies/dependencies:

```json
  "devDependencies": {
    "@seneca/maintain": "^0.0.20",
    "@types/jest": "^27.4.1",
    "@types/node": "^17.0.25",
    "esbuild": "^0.14.38",
    "esbuild-jest": "^0.5.0",
    "jest": "^27.5.1",
    "seneca-doc": "^2.1.3",
    "seneca-msg-test": "^3.2.0",
    "typescript": "^4.6.3"
  },
  "peerDependencies": {
    "@seneca/entity-util": ">=1",
    "seneca": ">=3",
    "seneca-entity": ">=16",
    "seneca-promisify": ">=2"
  }
```

However, this feature was only introduce in [Node.js 15+](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/). Therefore, if I'm not mistaken, this opens the door for potential bugs. As some packages will not be installed. 

For example: containers that uses some other current Node.js [Maintenance LTS](https://nodejs.org/en/about/releases/) version(e.g. Lambada environment - 14x).

A basic solution for this, will be to add the peerDeepencies to the devDependencies list, also. Allowing a good support for those who are working with previous versions of Node.js(at least until Node.js team provides some support for them):

```json
   "devDependencies": {
    "@seneca/entity-util": "^1.3.0",
    "@seneca/maintain": "^0.0.20",
    "@types/jest": "^27.4.1",
    "@types/node": "^17.0.25",
    "esbuild": "^0.14.38",
    "esbuild-jest": "^0.5.0",
    "jest": "^27.5.1",
    "seneca": "^3.26.2",
    "seneca-doc": "^2.1.3",
    "seneca-entity": "^16.4.0",
    "seneca-msg-test": "^3.2.0",
    "seneca-promisify": "^2.3.0",
    "typescript": "^4.6.3"
  },
  "peerDependencies": {
    "@seneca/entity-util": ">=1",
    "seneca": ">=3",
    "seneca-entity": ">=16",
    "seneca-promisify": ">=2"
  }
```

If you think this solution is suitable, I'm more than willing to open a PR enforcing this update.

**Comment by rjrodger** [comment]
This indeed intentional :)
Seneca plugins in actual use are not standalone - the app that uses them needs to have the peerdeps as actual deps

It does cause an issue for Github Actions unit testing this plugin standalone - you can see we do a manual install to handle that

**Comment by LeonNimoy** [comment]
I see. Thanks for the clarification. 👍🏾
